config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  root 'home#welcome'
  get 'sign_up', to: 'users#new', as: :sign_up
  post 'sign_up', to: 'users#create'

  get 'confirmations/confirm_email/:confirmation_token', to: 'confirmations#confirm_email', as: :email_confirmation
  get "login", to: "sessions#new", as: :login
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  def confirm!
    update_columns(confirmed_at: Time.current)
  end

  def confirmed?
    confirmed_at.present?
  end

  def unconfirmed?
    !confirmed?
  end

  def generate_confirmation_token
    signed_id expires_in: 15.minutes
  end

  def send_confirmation_email!
    confirmation_token = generate_confirmation_token
    UserMailer.confirmation(self, confirmation_token).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authenticated
end

app/controllers/concerns/authenticated.rb
module Authenticated
  extend ActiveSupport::Concern

  included do
    before_action :current_user
    helper_method :current_user
    helper_method :user_signed_in?
  end

  def current_user
    if session[:current_user_id]
      current_user ||= User.find_by(id: session[:current_user_id])
    end
  end

  def user_signed_in?
    current_user.present?
  end

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController

  def confirm_email
    @user = User.find_signed(params[:confirmation_token])

    if @user.present?
      @user.confirm!

      redirect_to root_path, notice: "Thank you, you have now confirmed your account"
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if @user.authenticate(params[:user][:password])
        reset_session
        session[:current_user_id] = @user.id
        redirect_to dashboard_index_path, notice: "Signed in."
      else
        flash.now[:alert] = "Incorrect email or password."
        render :new, status: :unprocessable_entity
      end
    else
      flash.now[:alert] = "Incorrect email or password."
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    reset_session
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_confirmation_email!
      redirect_to root_path, notice: 'A confirmation email has been sent to your registered email.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<%= render 'shared/navbar' %>
<h1>User Dashboard</h1>
<p>Welcome, <u><%= current_user.email %></u></p>

app/views/home/welcome.html.erb
<%= render 'shared/navbar' %>
<h2>Rails Authentication from Scratch</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Auth App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <mark>
        <%= notice %>
      </mark>
    <% elsif alert %>
      <mark>
        <%= alert %>
      </mark>
    <% end %>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav>
  <ul>
    <li><strong>Simple Auth App</strong></li>
  </ul>
  <ul>
    <% if user_signed_in? %>
    <li><%= link_to 'Log out', logout_path, data: { turbo_method: :delete } %></li>
    <% else %>
        <li><%= link_to 'Sign up', sign_up_path %></li>
        <li><%= link_to 'Login', login_path %></li>
    <% end %>
  </ul>
</nav>

app/views/users/new.html.erb
<h2>Sign up</h2>
<%= form_with model: @user, url: sign_up_path do |form| %>
  <label for="email">
    Email
    <%= form.email_field :email, required: true %>
  </label>
  <label for="password">
    Password
    <%= form.password_field :password, required: true %>
  </label>
  <label for="password_confirmation">
    Password Confirmation
    <%= form.password_field :password_confirmation, required: true %>
  </label>
  <%= form.submit "Sign Up" %>
<% end %>